### PR TITLE
image-builder/logging: fix crash for missing fields

### LINKED ISSUE #1248: nil deref crash
```[PANIC RECOVER] interface conversion: interface {} is nil, not logrus.Fields goroutine 26080 [running]:
main.main.RecoverWithConfig.func3.1.1()
	/go/src/github.com/osbuild/image-builder/vendor/github.com/labstack/echo/v4/middleware/recover.go:99 +0x150
panic({0xeaca80?, 0xc002676450?})
	/usr/lib/golang/src/runtime/panic.go:914 +0x21f
main.(*ctxHook).Fire(0xee7b80?, 0xc00043c380)
	/go/src/github.com/osbuild/image-builder/cmd/image-builder/logging.go:40 +0x249
github.com/sirupsen/logrus.LevelHooks.Fire(0xc0009365c0?, 0x936590?, 0x0?)
	/go/src/github.com/osbuild/image-builder/vendor/github.com/sirupsen/logrus/hooks.go:28 +0x70
github.com/sirupsen/logrus.(*Entry).fireHooks(0xc00043c380)
	/go/src/github.com/osbuild/image-builder/vendor/github.com/sirupsen/logrus/entry.go:280 +0x1fa
github.com/sirupsen/logrus.(*Entry).log(0xc00043c310, 0x4, {0xc00061f100, 0x628})
	/go/src/github.com/osbuild/image-builder/vendor/github.com/sirupsen/logrus/entry.go:242 +0x399
github.com/sirupsen/logrus.(*Entry).Log(0xc00043c310, 0x4, {0xc000936870?, 0x2?, 0x2?})
	/go/src/github.com/osbuild/image-builder/vendor/github.com/sirupsen/logrus/entry.go:304 +0x48
github.com/sirupsen/logrus.(*Entry).Logf(0xc00043c310, 0x4, {0x101ea37?, 0xd18c2e2800?}, {0xc000936948?, 0xc001b09ec0?, 0xc00048a418?})
	/go/src/github.com/osbuild/image-builder/vendor/github.com/sirupsen/logrus/entry.go:349 +0x7c
github.com/sirupsen/logrus.(*Entry).Infof(...)
	/go/src/github.com/osbuild/image-builder/vendor/github.com/sirupsen/logrus/entry.go:362
github.com/osbuild/image-builder/internal/oauth2.(*LazyToken).acquireNewToken(0xc0006e9d40, {0x1411470, 0x1be5000}, 0x20?)
	/go/src/github.com/osbuild/image-builder/internal/oauth2/lazy_token.go:55 +0x295
github.com/osbuild/image-builder/internal/oauth2.(*LazyToken).Token(0xc000936a80?, {0x1411470?, 0x1be5000?})
	/go/src/github.com/osbuild/image-builder/internal/oauth2/lazy_token.go:64 +0x1f
github.com/osbuild/image-builder/internal/clients/recommendations.(*RecommendationsClient).request(0xc0002070e0, {0xfe987d, 0x4}, {0xc00322eb40, 0x4e}, 0xc00048a3e0?, {0x140b5a8, 0xc001b09ec0})
	/go/src/github.com/osbuild/image-builder/internal/clients/recommendations/client.go:88 +0x2ae
github.com/osbuild/image-builder/internal/clients/recommendations.(*RecommendationsClient).RecommendationsPackages(0xc0002070e0, {{0xc001b57450, 0x1, 0x1}, 0x5})
	/go/src/github.com/osbuild/image-builder/internal/clients/recommendations/client.go:119 +0x154
github.com/osbuild/image-builder/internal/v1.(*Handlers).handleRecommendationsResponse(0xd3339c?, {0x1421cc0, 0xc0006a65a0}, {{0xc001b57450?, 0x1?, 0x1?}, 0x0?})
	/go/src/github.com/osbuild/image-builder/internal/v1/handler_recommend_package.go:34 +0x74
github.com/osbuild/image-builder/internal/v1.(*Handlers).RecommendPackage(0x0?, {0x1421cc0, 0xc0006a65a0})
	/go/src/github.com/osbuild/image-builder/internal/v1/handler_recommend_package.go:19 +0x9e
github.com/osbuild/image-builder/internal/v1.(*ServerInterfaceWrapper).RecommendPackage(...)
	/go/src/github.com/osbuild/image-builder/internal/v1/api.go:2368
github.com/osbuild/image-builder/internal/prometheus.PrometheusMW.func1({0x1421cc0, 0xc0006a65a0})
	/go/src/github.com/osbuild/image-builder/internal/prometheus/prometheus.go:76 +0x174
github.com/osbuild/image-builder/internal/v1.(*Server).ValidateRequest-fm.(*Server).ValidateRequest.func1({0x1421cc0, 0xc0006a65a0})
	/go/src/github.com/osbuild/image-builder/internal/v1/middleware.go:34 +0x2a2
github.com/osbuild/image-builder/internal/v1.(*Server).noAssociateAccounts-fm.(*Server).noAssociateAccounts.func1({0x1421cc0, 0xc0006a65a0})
	/go/src/github.com/osbuild/image-builder/internal/v1/middleware.go:53 +0xc9
github.com/osbuild/image-builder/internal/v1.Attach.WrapMiddleware.func5.1.1({0x140f6d8, 0xc00237b3e0}, 0xe397e0?)
	/go/src/github.com/osbuild/image-builder/vendor/github.com/labstack/echo/v4/echo.go:944 +0x9e
net/http.HandlerFunc.ServeHTTP(0xc001b098f0?, {0x140f6d8?, 0xc00237b3e0?}, 0xc0001ca776?)
	/usr/lib/golang/src/net/http/server.go:2136 +0x29
github.com/redhatinsights/identity.BasePolicy.func1({0x140f6d8, 0xc00237b3e0}, 0xc0021d0900)
	/go/src/github.com/osbuild/image-builder/ven...
```

```
{"@timestamp":"2024-06-25T15:30:35.317Z","@version":1,"app":"image-builder","caller":"github.com/osbuild/image-builder/internal/common.(*EchoLogrusLogger).Errorf","insights_id":"7fb1ca194eff47fda1272420f6a6fd12","levelname":"error","message":"Internal error 500: Internal Server Error, interface conversion: interface {} is nil, not logrus.Fields","method":"POST","path":"/api/image-builder/v1/experimental/recommendations","request_id":"35303331","source_host":"image-builder-service-5f58856b84-qggm4"}```

### PR DESCRIPTION
**Pull request by schuellerf**
also adding the missing tests

Fixes #1248

### CODE REVIEW

**Comment by schuellerf** [comment]
many other tests also fail locally now - I'll check those too

**Review by croissanne — APPROVED** [review]
thank you!

File: cmd/image-builder/logging.go [hunk 1]
```diff
@@ -34,10 +34,14 @@ func (h *ctxHook) Levels() []logrus.Level {
...
-		e.Data["insights_id"] = e.Context.Value(insightsRequestIdCtx)
-		rd := e.Context.Value(requestDataCtx).(logrus.Fields)
+	if e.Context == nil || e.Data == nil {
+		return nil
+	}
+
+	e.Data["request_id"] = e.Context.Value(requestIdCtx)
+	e.Data["insights_id"] = e.Context.Value(insightsRequestIdCtx)
+
+	if rd, ok := e.Context.Value(requestDataCtx).(logrus.Fields); ok {
```
Comment (lzap) [inline cmd/image-builder/logging.go:44]: TIL it appears that once you add the second return value (`ok`) then Go [will not generate code that errors out](https://play.golang.com/p/frb-81Do8Fv). So this will work as expected.

**Review by lzap — APPROVED** [review]
Thanks!
